/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDiscountDB } from "./IDiscountDB";
export type { IERC721Metadata } from "./IERC721Metadata";
export type { ISoulBoundToken } from "./ISoulBoundToken";
export type { ISoulink } from "./ISoulink";
export type { ISoulinkMinter } from "./ISoulinkMinter";
