/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISoulinkMinter,
  ISoulinkMinterInterface,
} from "../../../contracts/interfaces/ISoulinkMinter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "db",
        type: "address",
      },
    ],
    name: "SetDiscountDB",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "feeTo",
        type: "address",
      },
    ],
    name: "SetFeeTo",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint96",
        name: "limit",
        type: "uint96",
      },
    ],
    name: "SetLimit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint96",
        name: "mintPrice",
        type: "uint96",
      },
    ],
    name: "SetMintPrice",
    type: "event",
  },
  {
    inputs: [],
    name: "discountDB",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feeTo",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "limit",
    outputs: [
      {
        internalType: "uint96",
        name: "",
        type: "uint96",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "discount",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "mintPrice",
    outputs: [
      {
        internalType: "uint96",
        name: "",
        type: "uint96",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "soulink",
    outputs: [
      {
        internalType: "contract ISoulink",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISoulinkMinter__factory {
  static readonly abi = _abi;
  static createInterface(): ISoulinkMinterInterface {
    return new utils.Interface(_abi) as ISoulinkMinterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISoulinkMinter {
    return new Contract(address, _abi, signerOrProvider) as ISoulinkMinter;
  }
}
