/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as discountDbSol from "./DiscountDB.sol";
export * as interfaces from "./interfaces";
export * as standards from "./standards";
export * as test from "./test";
export { Soulink__factory } from "./Soulink__factory";
export { SoulinkMinter__factory } from "./SoulinkMinter__factory";
