/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1271",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1271__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "DiscountDBV0",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiscountDBV0__factory>;
    getContractFactory(
      name: "IDiscountDB",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiscountDB__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "ISoulBoundToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISoulBoundToken__factory>;
    getContractFactory(
      name: "ISoulink",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISoulink__factory>;
    getContractFactory(
      name: "ISoulinkMinter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISoulinkMinter__factory>;
    getContractFactory(
      name: "Soulink",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Soulink__factory>;
    getContractFactory(
      name: "SoulinkMinter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SoulinkMinter__factory>;
    getContractFactory(
      name: "SoulBoundToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SoulBoundToken__factory>;
    getContractFactory(
      name: "ERC721Mock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Mock__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1271",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1271>;
    getContractAt(
      name: "ERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "IERC721Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "DiscountDBV0",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiscountDBV0>;
    getContractAt(
      name: "IDiscountDB",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiscountDB>;
    getContractAt(
      name: "IERC721Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "ISoulBoundToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISoulBoundToken>;
    getContractAt(
      name: "ISoulink",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISoulink>;
    getContractAt(
      name: "ISoulinkMinter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISoulinkMinter>;
    getContractAt(
      name: "Soulink",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Soulink>;
    getContractAt(
      name: "SoulinkMinter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SoulinkMinter>;
    getContractAt(
      name: "SoulBoundToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SoulBoundToken>;
    getContractAt(
      name: "ERC721Mock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721Mock>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
